CONNECT 'C:\DotNetCoreProjects\Console_EF_FB_1\Console_EF_FB_1\FBDatabase\FB_DATABASE_1.FDB' USER 'SYSDBA' PASSWORD 'masterkey';

CREATE DOMAIN TDATUM_PLAT_DO AS 
DATE
DEFAULT '2999-12-31';

CREATE DOMAIN TDATUM_PLAT_OD AS 
DATE
DEFAULT '1990-01-01';

CREATE DOMAIN TID AS 
CHAR(20);

CREATE DOMAIN TKOD AS 
CHAR(10);

CREATE DOMAIN TLOGIN AS 
VARCHAR(25) CHARACTER SET WIN1250
COLLATE WIN_CZ;

CREATE DOMAIN TPOPIS AS 
VARCHAR(100) CHARACTER SET WIN1250
COLLATE WIN_CZ;

CREATE DOMAIN TPOZNAMKA AS 
VARCHAR(255) CHARACTER SET WIN1250
COLLATE WIN_CZ;

CREATE DOMAIN TTIMESTAMP AS 
TIMESTAMP;

CREATE DOMAIN TVARCHAR100 AS 
VARCHAR(100) CHARACTER SET WIN1250
COLLATE WIN_CZ;

CREATE TABLE CAT_OSOBA_TYP (
  ID                      TID NOT NULL,
  DATETIME                TTIMESTAMP NOT NULL,
  LOGIN                   TLOGIN NOT NULL,
  OSOBATYP_KOD            TKOD NOT NULL,
  OSOBATYP_POPIS          TPOPIS NOT NULL,
  OSOBATYP_PLAT_OD_DATUM  TDATUM_PLAT_OD NOT NULL,
  OSOBATYP_PLAT_DO_DATUM  TDATUM_PLAT_DO NOT NULL,
  OSOBATYP_POZN           TPOZNAMKA,
  PRIMARY KEY(ID)
);

CREATE VIEW VCAT_OSOBA_TYP (
    ID,
    DATETIME,
    LOGIN,
    OSOBATYP_KOD,
    OSOBATYP_POPIS,
    OSOBATYP_PLAT_OD_DATUM,
    OSOBATYP_PLAT_DO_DATUM,
    OSOBATYP_POZN,
    VALID_FLAG)
AS
  SELECT
    ID,
    DATETIME,
    LOGIN,
    OSOBATYP_KOD,
    OSOBATYP_POPIS,
    OSOBATYP_PLAT_OD_DATUM,
    OSOBATYP_PLAT_DO_DATUM,
    OSOBATYP_POZN,
    CASE
      WHEN CURRENT_DATE BETWEEN OSOBATYP_PLAT_OD_DATUM AND OSOBATYP_PLAT_DO_DATUM THEN 'Y'
      ELSE 'N'
    END VALID_FLAG
  FROM
    CAT_OSOBA_TYP;

CREATE TABLE ENT_OSOBA (
  ID                      TID NOT NULL,
  DATETIME                TTIMESTAMP NOT NULL,
  LOGIN                   TLOGIN NOT NULL,
  OSOBATYP_ID             TID NOT NULL,
  PRIMARY KEY(ID)
);

ALTER TABLE ENT_OSOBA ADD FOREIGN KEY (OSOBATYP_ID) REFERENCES CAT_OSOBA_TYP (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE TABLE ENT_FYZ_OSOBA (
  ID                 TID NOT NULL,
  FYZOSOBA_PRIJMENI  TVARCHAR100 NOT NULL,
  FYZOSOBA_JMENO     TVARCHAR100 NOT NULL,
  FYZOSOBA_DAT_NAR   DATE,
  FYZOSOBA_POZN      TPOZNAMKA,
  PRIMARY KEY(ID)
);

ALTER TABLE ENT_FYZ_OSOBA ADD FOREIGN KEY (ID) REFERENCES ENT_OSOBA (ID) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE VIEW V_FYZ_OSOBA (
  ID,
  DATETIME,
  LOGIN,
  OSOBATYP_ID,
  FYZOSOBA_PRIJMENI,
  FYZOSOBA_JMENO,
  FYZOSOBA_DAT_NAR,
  FYZOSOBA_POZN)
AS
  SELECT
      A.ID,
      A.DATETIME,
      A.LOGIN,
      A.OSOBATYP_ID,
      B.FYZOSOBA_PRIJMENI,
      B.FYZOSOBA_JMENO,
      B.FYZOSOBA_DAT_NAR,
      B.FYZOSOBA_POZN
    FROM ENT_OSOBA A
      INNER JOIN ENT_FYZ_OSOBA B ON B.ID = A.ID;

SET TERM ^;

CREATE TRIGGER V_FYZ_OSOBA_INSERT FOR V_FYZ_OSOBA 
  ACTIVE BEFORE INSERT AS 
    BEGIN 
      INSERT INTO ENT_OSOBA VALUES (NEW.ID, NEW.DATETIME, NEW.LOGIN, NEW.OSOBATYP_ID); 
      INSERT INTO ENT_FYZ_OSOBA VALUES (NEW.ID, NEW.FYZOSOBA_PRIJMENI, NEW.FYZOSOBA_JMENO, NEW.FYZOSOBA_DAT_NAR, NEW.FYZOSOBA_POZN); 
    END ^
    
CREATE TRIGGER V_FYZ_OSOBA_UPDATE FOR V_FYZ_OSOBA
  ACTIVE BEFORE UPDATE AS 
    BEGIN 
      UPDATE ENT_OSOBA SET 
          DATETIME = NEW.DATETIME,
          LOGIN = NEW.LOGIN,
          OSOBATYP_ID = NEW.OSOBATYP_ID
        WHERE ID = OLD.ID; 
      UPDATE ENT_FYZ_OSOBA SET 
          FYZOSOBA_PRIJMENI = NEW.FYZOSOBA_PRIJMENI,
          FYZOSOBA_JMENO = NEW.FYZOSOBA_JMENO,
          FYZOSOBA_DAT_NAR = NEW.FYZOSOBA_DAT_NAR,
          FYZOSOBA_POZN = NEW.FYZOSOBA_POZN
        WHERE ID = OLD.ID; 
    END ^
  
CREATE TRIGGER V_FYZ_OSOBA_DELETE FOR V_FYZ_OSOBA 
  ACTIVE BEFORE DELETE AS 
    BEGIN 
      DELETE FROM ENT_FYZ_OSOBA WHERE ID = OLD.ID; 
      DELETE FROM ENT_OSOBA WHERE ID = OLD.ID; 
    END ^
  
SET TERM ;^ 
           